### ISSUE TITLE
Replace app logo with updated one 

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#145]
- [ ] replace app logo on auth screens
- [ ] replace app icon
- [ ] replace icon on splash screen

Note: for splash screen you can use any variation of logo

<img width="217" alt="Screenshot 2023-09-01 at 04 47 00" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/93ad6740-c85a-46cb-9bd9-9357ecc0faef">

**Comment by k-mlch** [comment]
@danilittaa hi! I'm testing this ticket and I've noticed that the logo is a bit blurred, especially in comparison with the title, could you clarify if it was done in such a way on purpose by design? 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/d3a3be82-5253-4224-a7cb-6c6c0b479641)

**Comment by danilittaa** [comment]
@k-mlch, I didn't even notice that. Okay, I'll change the image from PNG to SVG then.

**Comment by k-mlch** [comment]
@danilittaa thank you, i will move the ticket in To Do column then, so you can pick it up
