### ISSUE TITLE
Authorization token

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#16]
Implement JWT Token signing+verification

https://www.npmjs.com/package/jose

 - [ ] JWT token is generated and returned by Sign In / Sign Up
 - [x] JWT token stores userId
 - [x] JWT token is stored in localStorage

**Comment by vladyslavdobychin** [comment]
High level implementation plan: 

- Locate Sign-in/Sign-up requests - how the request is sent from the front end. 
- Locate on the backend where the Sign-in/Sign-up requests are received and handled. 
- Add the logic to issue the JWT token after the successful verification.
- The verification process for the user should include the user ID, attach the user ID to JWT payload.
- The server needs to respond to the client after the verification, attach the token to the response body. 
- Locate on the client side where the response is received and save the token in the local storage

**Comment by vladyslavdobychin** [comment]
Plan for updating the pull request: 

- [x] In the backend, in users.ts import config from #libs/packages/config/config.ts instead of creating a new instance 
- [x]  Remove comment from front end. 
- [x]  Create a separate JWT service. 
     - [x] Relocate the instance of JWT service to auth.ts 
     - [x] Update JWT service to receive the alg just like the secret key
     - [ ] Look into the option of turning the secret key and alg into their own variables and import them where needed
- [x] Add ALG as a parameter to the base-config.package.ts
- [x] Fix the CI issues with UserSignUpResponseDto not having a token
- [x] Remove build from included in the shared ts config
- [x] Make sure jose was removed from front-end 

TBD: 
- Clarify the necessity of including the build directory in the shared ts config 
> Was discussed, per Volodymyr Minchenko: That is the issue with eslint plugin and it won't influenced to linting the project. Typescript should check only src/ folder

**Comment by vladyslavdobychin** [comment]
Previous changes were mostly accepted, adding new: 

- [x] Use Storage service instead of local storage on frontend 
- [x] Solve the problem with circular dependencies in the backend in users.ts 
>  [Per Vladimir](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/pull/37#issuecomment-1689418394), the issue is cause by importing the user service to auth, which contains JWT service, and import JWT to user. As a solution, move JWT service to a separate module to **libs/packages/**

- [x] Figure out how to send token [separately](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/pull/37#discussion_r1301862871), there should be a PR with it already. 
- [x] Rename authStorage to storage in [auth-api](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/pull/37#discussion_r1301858018). 
            Fixed it but by changing the storage property to protected in BaseHttpApi
- [x] Remove package-lock.json from frontend and backend directories. 
- [x] Remove [**await**](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/pull/37#discussion_r1301854724) from signJWT method

**Comment by vladyslavdobychin** [comment]
Adding new changes: 

- [x] Move UserAuthResponseDto to a separate file. 
- [x] Move saving a token to the local storage into the SignUp action.
