### ISSUE TITLE
Add sign out functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#167]
- [x] Add "Sign out" button to profile screen
- [x] After user clicks on this button, they should be redirected to Sign In

<img width="249" alt="Screenshot 2023-09-03 at 16 02 08" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/c2c265a4-94b7-4d19-9e6d-64cabd5ac746">

**User Story:**
As a user, I want to have the ability to log out of my account on my mobile phone when needed so that no one can get access to it.

**Acceptance Criteria:**
- The "Sign Out" button should be located on the user's profile page.
- After clicking on it all user should be logged out and navigated to the sign in page

**Comment by iamAlinaaa** [comment]
@Liza-Veis Hello ) i have some questions
We have this ternary operator and render these components in particular case. if i now make simple redirection to sign in it won`t work , because user already authenticated. Should i just delete current authenticated user from redux ?
![Снимок экрана 2023-09-04 105501](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/73c7f7bd-861d-4ba3-9ffe-44d9a5151400)

**Comment by liza-veis** [comment]
Yes

**Comment by iamAlinaaa** [comment]
@Liza-Veis Do we need to create dto type (i dont know what to write there, because it returns nothing, we just need to remove user credentials from redux) and ApiAuthPath like  SIGN_OUT: '/sign-out', in shared ?
 it works perfectly without it like on **(image 1)** and **(video 1**). 
but if I create ApiAuthPath like  SIGN_OUT: '/sign-out', (without dto type still) and use auth-api **(image 2)** i get error notification **(image 3)** but all is working too


(Image 1)
![Снимок экрана 2023-09-05 143813](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/ae5c5e14-a4fe-40a1-a677-df8ce9066bdf)

 (image 2) 
![Снимок экрана 2023-09-05 144325](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/81c5a811-b001-4dc7-83af-63aad9f36209)

 (image 3)
![Снимок экрана 2023-09-05 144229](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/290681b9-3596-4082-b8c6-a526c7de4fae)

(video 1)
https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/66a46832-390b-4f93-b533-b2929192d0cd

**Comment by liza-veis** [comment]
we don't need to call api, just remove token from storage and user from store

**Comment by iamAlinaaa** [comment]
@Liza-Veis hello )  writing here in comments this task is blocked by #113 , because it requires code that implemented in #113
