### ISSUE TITLE
[BUG] User is unable to sign in/sign up on the Development env

### ISSUE THREAD

**Issue by KrychkovskaVira** [BinaryStudioAcademy/bsa-2023-calmpal#180]
**Description:**
The error "password authentication failed for user 'postgres'" occurs when attempting to sign in/sign up to the developer environment

**Environment:**
http://calmpal-alb-development-453467742.eu-west-1.elb.amazonaws.com/

**Steps to reproduce:**
Navigate to the Development environment link

**Actual Result:**
The error "password authentication failed for user 'postgres'" occurs when attempting to sign in/sign up to the developer environment

**Expected Result:**
Attempting to sign in/sign up to the developer environment is successful, user is redirected to survey or main page.

**Visual Proof (screenshots, videos, text):**

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/392f9f42-ce15-444e-af3d-e57ac4fa9324)
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/88768615/46f75965-c8bc-4295-b105-6f633b1d30a4)

**Severity:**
Critical (S1)

**Comment by v0ldemar01** [comment]
The solution [link](https://stackoverflow.com/questions/60091149/update-environment-variable-secrets-in-an-ecs-container)

**Comment by v0ldemar01** [comment]
Proposed solution is not fully suitable for our case. The reason is managed Secrets Manager instance via RDS. UpdateSecretVersionStage event updated the credentials on RDS due to new secrets. So after it we had better update force new deployment of current ECS service. The main issue is caused due to automation rotation of secrets. If the secret is subsequently updated or rotated, the container doesn't receive the updated value automatically.
