### ISSUE TITLE
Load and seed meditation entries

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#192]
- [x] when user clicks on meditation item on meditation sidebar #188, all meditation entries should be loaded
- [x] find some meditations (10-20), you can use spotify, soundcloud etc.
- [x] ask @v0ldemar01 to upload these meditations to s3
- [x] create seeds to seed database with these meditation entries

**Comment by OlesiaTr** [comment]
@v0ldemar01 hi! I think [this album](https://soundcloud.com/user-992839308/sets/med?utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing) will work, it doesn't have any ads inside the songs as far as I noticed. Could you, please, upload them?

**Comment by v0ldemar01** [comment]
@OlesiaTr could you please send me an archive of downloaded ones please

**Comment by OlesiaTr** [comment]
@v0ldemar01 yes, ok)

**Comment by OlesiaTr** [comment]
Couple of clarifications that I need: 
1. Structurally wise, is it better to create seeds/ and seed-data/ folders in the backend/db or do you want me to keep data in the same file, as a seed?
2. Right now for meditation_entries we have 

```
  ID: 'id',
  TOPIC_ID: 'topic_id',
  CREATED_AT: 'created_at',
  UPDATED_AT: 'updated_at',
```
Do you want me to add smth like this? Because I see this data is used in the Figma designs.
```
  {
    title: 'Meditation 1',
    description: 'Description of Meditation 1',
    duration: '10 minutes',
    audioS3Key: 'meditations/Meditation1.mp3',
  }
```

3. Also in the Figma design and what we have right now on the development branch, I see that we have the same img for the songs, I don't need to add any in the seed, correct?

**Comment by liza-veis** [comment]
> Structurally wise, is it better to create seeds/ and seed-data/ folders in the backend/db or do you want me to keep data in the same file, as a seed?

yes, the first option as it's done in mini project

> Do you want me to add smth like this? Because I see this data is used in the Figma designs.

We need to add media_url and content type take a look at #213 where we will add them, looks like your pr depends on it

> Also in the Figma design and what we have right now on the development branch, I see that we have the same img for the songs, I don't need to add any in the seed, correct?

yes, you don't need to add image for now
