### ISSUE TITLE
Add meditation entry functionality

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#283]
- [ ] add an ability to create meditation with audio uploading (mp3 only for now) 
- [ ] create a modal on ui (for now, we don't have design so just try to stick to the same style)
- [ ] when user clicks add button in meditations sidebar, "Add meditation" modal should appear

**Comment by danilittaa** [comment]
@Liza-Veis , I have a bunch of questions about my task right now. I looked at how this task appears in the web version, and I can see that it looks slightly different from what I have done. I'll try to explain as clearly as possible. 

In the web version, the 'Add' button is located in the sidebar (which, if translated to mobile language, is on the MeditationHome screen). When a user adds a new track, a new meditation component appears on the right side of the screen (rather than in the sidebar, as I implemented). If I understand correctly, I need to move the 'Add new meditation' button from the MeditationHome screen to the MeditationScreen and add a new meditation there, right? But then, I don't quite understand the purpose of the sidebar (MeditationHome screen). If there are different categories there (for example, Meditations, Breath Exercise), don't we need additional backend logic to ensure that we add a new meditation to the specific category?

**Comment by liza-veis** [comment]
>  If I understand correctly, I need to move the 'Add new meditation' button from the MeditationHome screen to the MeditationScreen and add a new meditation there, right? 
yes

> But then, I don't quite understand the purpose of the sidebar (MeditationHome screen). If there are different categories there (for example, Meditations, Breath Exercise), don't we need additional backend logic to ensure that we add a new meditation to the specific category?

it's a separate pages, for now we have only one `Meditations`, but in future we will have Breathing Exercise and other items. And all of them will have different logic, they are not meditation topics

**Comment by danilittaa** [comment]
@Liza-Veis , Should I also add logic for the meditation to play, or is that a separate task, and I just need to create meditations?

**Comment by liza-veis** [comment]
Yes, you only need to add meditation

**Comment by k-mlch** [comment]
@danilittaa 

Here are some issues that i found:

1. I can't fully test this feature because of [this ticket](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/issues/282) meditations are uploaded as topics (options in the sidebar) and not added to the list of meditations, so uploading functionality should be retested after 282 will be merged

2. Montserrat Font should be used for all the text on the 'Add meditation' screen (same as on Web application)

3. 'Click here' should start from Capital letter

4. First input field should be called 'Meditation name' and the placeholder should be 'Enter meditation name'

5.  When I click 'click here' but do not select any file and just return to the screen then i receive an Error notification

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/faa9a7cd-5b38-4f57-af49-d1df0ae1546a

**Comment by k-mlch** [comment]
@danilittaa 

when i upload my meditation and then open it, another meditation is opened 


https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/05c6ec1f-3eb2-4390-9bff-aed8591b854e

**Comment by danilittaa** [comment]
@k-mlch , my task was only to add meditations, not to play them

**Comment by k-mlch** [comment]
@danilittaa Is showing correctly track length on the cards also not related to this task? 
<img width="136" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/747c625c-fe5d-4427-9283-18087b2776ec">

**Comment by danilittaa** [comment]
@k-mlch, it also does not relate to my task

**Comment by k-mlch** [comment]
@danilittaa i see, thank you, i've created separate ticket for those issues

**Comment by danilittaa** [comment]
@k-mlch , no, all there issue are fixed in my pr Meditation Timer (it is not merged yet)
