### ISSUE TITLE
Improvements to the Sign Up page on Mobile app

### ISSUE THREAD

**Issue by k-mlch** [BinaryStudioAcademy/bsa-2023-calmpal#299]
1. Make the sign form centered on the screen, so that it has the same space from the top and from the bottom.
For now, when i open the form on my phone it has a space on the top and no space on the bottom. 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/66c4cb68-8ee7-4539-8869-f6fc2f1fff71)

2. When i input text into the field the color of the text is white so i don't see what i'm typing (the color depends on the mobile settings but should be set to the black

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/c6a80345-e945-4872-a6b4-31d38bf3fdec)

3. Make the size of the title less so that it doesn't take 4 lines on the phone screen (should take max 3 lines)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/9cfd6b90-0dd6-45e9-94e9-5d6463438714)

**Comment by k-mlch** [comment]
@iamAlinaaa i can't test issue with white color of text because i didn't have this issue on my phone, can you send me a screenshot how it looks now?

and also the last sentence doesn't fit into one line, is it possible to make the whole form on sign up page and sign in page a little wider (make spaces from left and right smaller) so that the text fits into one line on the screen (for example same size as on web version of out app)? 

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/eba5bd69-8543-4e30-96a9-e74b76a0436b)

**Comment by iamAlinaaa** [comment]
@k-mlch yeah, the color has changed, so it looks good now, but i still have white color on search input. and i dont know how to make the whole form on sign up page and sign in page a little wider, because it will not solve the problem, as we have quite big fon tfor this (you can look on screens). to achieve this layout i can reduce the font size and change padding, and then it will work
![IMG_4461](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/2b598684-c79b-4660-899b-f0cd1d4f409e)
![IMG_4460](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/7a1818d4-54cd-4b8a-859c-0dbf87787e11)
![IMG_4459](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/111873795/e6a8b3da-60af-4843-ace3-84892d7c6415)

**Comment by k-mlch** [comment]
@iamAlinaaa will it be readable with a smaller font, did u try it? also if the screen size is smaller than your phone will those users still face this issue or it will be adapted to their screen size and will stay as one-line text?

**Comment by iamAlinaaa** [comment]
@k-mlch we cant predict will it be one line text or not, because i have no ability to try it on all phones, but i guess there will be more chances for this line to be one line text . So ill make fixes to this branch
