### ISSUE TITLE
Add user_roles table

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#52]
- [x] Add user_roles table according to db schema in readme
- [x] Add role_id column to user 
- [x] Already existed and new users should have role 'user'

Acceptance criteria: 
1. The user_roles table has been created with columns as specified in the database schema in the README
2. The role_id column has been added to the user table
3. When adding the role_id to the user table, all existing users have their role_id set to 'user'

**Comment by OlesiaTr** [comment]
Hello! As far as I understood, we mustn't change previous migration table, so I added role_id column with a new migration that alters the users table. But I can't figure out how exactly am I supposed to add user role to all the users. Should it be separate function/method? Because if I will just assign it - existing users wont have this changes

**Comment by v0ldemar01** [comment]
@OlesiaTr Hey, so you need to create a new migration, alter table and add new column role_id. Then iterate existing users with modiify role_id column with setting appropriate value. Add constraint for role_id notNullable. If it is not clear please ping me
