### ISSUE TITLE
Chat layout

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#60]
- [ ] Build basic chat layout (all data will be mocked)
- [ ] Add input field and send button at the bottom
- [ ] Message is required
- [ ] When user presses send button, the message should appear on screen
- [ ] User should be able to get to this screen by clicking item on Chat Screen #54 

![Chat](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/669ad093-4884-4436-872b-6903e73974df)

**Comment by oksana-mlynska** [comment]
@danilittaa 
1. 
Actual result: After opening the selected chat screen, the top of chat history is displayed and then it jumps down to the latest messages.
Expected result: The latest chat history is displayed, If the first messages from the chat history doesn't fit to the screen, they are not displayed until the user scrolls up.

https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/1536655c-55e6-4db6-84d6-a2dd733fd9fa

**Comment by oksana-mlynska** [comment]
@danilittaa 
2.  "Doctor Freid.ai" label is not displayed on the chat screen next to the received messages


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/805a5f2e-5d20-4af9-9648-3cb5f092a431)

**Comment by oksana-mlynska** [comment]
@danilittaa 
If we are showing this screen on the demo, maybe we should delete duplicating messages


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140756353/d73ab90d-74f2-4eb0-872f-452b57a2774f)

**Comment by oksana-mlynska** [comment]
@danilittaa is there a validation for the number of symbols in the input field?

**Comment by danilittaa** [comment]
@oksana-mlynska , 
1) I'm not really sure if it's worth implementing this right now. I think we should do it when we work with real data. @Liza-Veis , what do you say? 
2) I just used a blue background because, as far as I know, the chat avatar will be generated later. @Liza-Veis , correct me if I'm wrong. 
3) Okay. 
4) No, do you think we should create it? Again, maybe we should focus on this when the backend is implemented and when we use real data, because right now I have no idea what the limit should be. @Liza-Veis , please advise if I'm wrong

**Comment by oksana-mlynska** [comment]
@danilittaa ok, let's wait for Liza's reply. If she says that we should postpone all these points for later, then I will close the issue.

**Comment by liza-veis** [comment]
1) yes, we will implement this after adding real data
2) this avatar won't be generated, so let's change it
4) let's add validation after backend part is implemented

**Comment by oksana-mlynska** [comment]
@danilittaa then please fix 2 and 3 and after that I will be able to close the issue.
