### ISSUE TITLE
Swagger documentation is not public

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#72]
**Description:**
When attempting to access swagger documentation via the route /documentation, a 401 error is returned, preventing users from accessing the documentation

**Preconditions:**
None

**Environment:**
None
**Steps to reproduce:**

1. Run backend application
2. Go to /v1/documentation route

**Actual Result:**
401 error returned

**Expected Result:**
User should see swagger documentation even if they are not signed in

**Visual Proof (screenshots, videos, text):**
None

**Severity:**
Minor (S3)

**Comment by HIMDanny** [comment]
@Liza-Veis, should I name the branch with a fix prefix for this issue branch?

**Comment by HIMDanny** [comment]
@Liza-Veis, I've noticed that even if I make the `/api/v1/documentation` route public, it is not found anyway. Is it ok?

**Comment by liza-veis** [comment]
Hey) checked this, yes you are right, it's not accessible from the frontend we will fix this later, for now let's make it accessible from the server

**Comment by liza-veis** [comment]
Updated the issue

**Comment by HIMDanny** [comment]
but there is another issue) `request.routerPath` does not recognize the documentation path. It tells that we are requesting the `/*` route. To my mind, it is because the fastify does not recognize this route as registered. Please, correct me, if I am wrong. I could change the `request.routerPath` to `request.url` in the whitelist checker, so it will be recognized as `api/v1/documentation`. But is it a good option? https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/blob/479b667920e0903d223fd70ff12cf9554b3c8aae/backend/src/libs/plugins/authorization/authorization.plugin.ts#L25

**Comment by liza-veis** [comment]
let's create a SERVED_PAGE_PATH const that equals to '/*' and skip it in authorization plugin

**Comment by HIMDanny** [comment]
ok, but it would accept all unregistered routes. Is it fine?
