### ISSUE TITLE
Add meditation player layout

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2023-calmpal#78]
- [x] Add meditation player layout (use mocked data for now)
- [x] User should be able to play audio by url

![Meditation & Breathing](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/64521658/37e5bfba-05cc-4033-bc38-82d9519d0a91)

**Comment by OlenaYatseniuk** [comment]
Please, notice that this component hasn't been put anywhere, so to test it you could add this component somewhere in index ts in the frontend folder to see it.

**Comment by k-mlch** [comment]
@OlenaYatseniuk 
hi, i found some issues related to the meditation player layout:

1. Missing subtitle for the tracks
<img width="606" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/9dacf7bd-0d1f-418b-9058-57e99a3b2a58">

2. No Back button on the Meditation Player screen (there is no way to return to the list of meditations either)
<img width="155" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/622ef06e-05c4-44c6-83dd-4d7bcd6cb546">

3. When I'm on the Meditation Player page and click on the 'Meditation' topic card I expect to navigate to the list of meditations but after i click nothing happens

4. Sometimes layout is not responsive for example:
**773x727**
<img width="831" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/3eb4c4a5-0904-4d80-a945-7193bfda8d2d">

**320x727**

<img width="347" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/ac7fbe4c-ff95-434e-af36-cc428ab4837d">

5. On my mobile device the player looks like this, is it possible for it to adapt to the center of the screen because now it's positioned too low when u open it on your real device?
![telegram-cloud-photo-size-2-5230992746456668029-y](https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/a0b9f038-a836-4989-a132-c3ae5e25f92c)

6. Can we make timeline shorter more similar to the Figma mockup?
<img width="633" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-calmpal/assets/140718705/60a8906f-971b-4384-b6a3-5454bcfa36ea">

**Comment by OlenaYatseniuk** [comment]
Thanks! Actually, after I created this mockup, @vladyslavdobychin has been working on it. So @vladyslavdobychin , could you tell me, please, why you deleted the subtitle? Is it a requirement or did you miss it?

**Comment by vladyslavdobychin** [comment]
> Thanks! Actually, after I created this mockup, @vladyslavdobychin has been working on it. So @vladyslavdobychin , could you tell me, please, why you deleted the subtitle? Is it a requirement or did you miss it?

Hi there! 
Well, I can't recall deleting it, tbh

**Comment by OlenaYatseniuk** [comment]
@vladyslavdobychin Hmm... okay. It seems to me that I added this, but never mind. I just thought that you made a lot of improvements to my initial code, so maybe you should assign yourself to this task too? What do you think about it?
If not, I will try to fix all these bugs by myself.

**Comment by vladyslavdobychin** [comment]
> @vladyslavdobychin Hmm... okay. It seems to me that I added this, but never mind. I just thought that you made a lot of improvements to my initial code, so maybe you should assign yourself to this task too? What do you think about it?
> If not, I will try to fix all these bugs by myself.

I absolutely don't mind, I honestly cant recall making changes to the layout of the player, but I'm fine with assigning myself to this task. I will get to it tomorrow in the morning, okay?

**Comment by OlenaYatseniuk** [comment]
Oh, I see, maybe they are my bugs with the layout, so it's unfair to ask you for help.

**Comment by OlenaYatseniuk** [comment]
@Liza-Veis Hi! I have a question about the subtitle. When I created this layout I had this subtitle, but now, after some changes, I cannot see it. Also, I see that in our db we don't have a column for this purpose. So, should we change the requirement not to have this? Or is it a bug?  If so, I think we need to create a new issue for this, as we need to make a new migration and add this to create meditation modal too. So what do you think?

**Comment by liza-veis** [comment]
No, we don't need to add it

**Comment by OlenaYatseniuk** [comment]
Great, thanks!

**Comment by OlenaYatseniuk** [comment]
@k-mlch These bugs were fixed and merged, so you can check it again!
